d1 = dlmread('C:\\b_T0.txt',' ');
d2 = dlmread('C:\\b_T1.txt',' ');
d3 = dlmread('C:\\b_T2.txt',' ');
d4 = dlmread('C:\\b_T3.txt',' ');
d5 = dlmread('C:\\b_T4.txt',' ');
d6 = dlmread('C:\\b_T5.txt',' ');
d7 = dlmread('C:\\b_T6.txt',' ');
d8 = dlmread('C:\\b_T7.txt',' ');
d9 = dlmread('C:\\b_T8.txt',' ');
d10 = dlmread('C:\\b_T9.txt',' ');
d11 = dlmread('C:\\b_T10.txt',' ');
filename = 'B_CDF';

linestyle = ['--','-','-.','.'];
color = ['r','b','g','c','m'];
legendpos = 'Best';
marker = ['s','o','^','v','d'];
lw = 4.0;
ms = 10;
fs = 16;
% legendkey = {'Per Flow','T=1','T=2','T=4','T=6', 'T=12'};
% legendkey = {'N=12','N=6','N=4','N=3','N=2', 'N=1'};
% legendkey = {'Per Flow','T=1','T=5','T=10'};
legendkey = {'Per Flow','T=1','T=2','T=3','T=4','T=5','T=6','T=7','T=8','T=9','T=10'};


[h1, stat1] = cdfplot(d1);
% set(h1, 'LineStyle','-','color','r','LineWidth',lw, 'Marker','o','MarkerSize',4);
set(h1, 'LineStyle','-','color','r','LineWidth',lw);
hold on;
[h2, stat2] = cdfplot(d2);
set(h2, 'LineStyle','-','color','b','LineWidth',lw);
hold on;
[h3, stat3] = cdfplot(d3);
set(h3, 'LineStyle','-.','color','g','LineWidth',lw);
hold on;
[h4, stat4] = cdfplot(d4);
set(h4, 'LineStyle','-.','color','c','LineWidth',lw);
hold on;
[h5, stat5] = cdfplot(d5);
set(h5, 'LineStyle','--','color','m','LineWidth',lw);
hold on;
[h6, stat6] = cdfplot(d6);
set(h6, 'LineStyle','--','color','y','LineWidth',lw);
hold on;
[h7, stat7] = cdfplot(d7);
set(h7, 'LineStyle','-','color','k','LineWidth',lw);
hold on;
[h8, stat8] = cdfplot(d8);
set(h8, 'LineStyle','-','color',[0.5 0 0],'LineWidth',lw);
hold on;
[h9, stat9] = cdfplot(d9);
set(h9, 'LineStyle','-.','color',[0.5 0.5 0],'LineWidth',lw);
hold on;
[h10, stat10] = cdfplot(d10);
set(h10, 'LineStyle','-.','color',[0.5 0 0.5],'LineWidth',lw);
hold on;
[h11, stat11] = cdfplot(d11);
set(h11, 'LineStyle','--','color',[0 0.5 0.5],'LineWidth',lw);

hold off;
title('');
xlabel('Total Completion Time','FontSize', fs, 'FontName', 'Arial');
ylabel('');
legend(legendkey,'Location', 'NorthEast');
set(gcf,'position',[100 100 640 320]);
set(gca, 'FontSize', fs, 'FontName', 'Arial','YGrid','on');
%set(gca, 'xscale', 'log');
set(gcf,'PaperPositionMode','auto');
print('-r0','-depsc', strcat(filename, '.eps'));
% ps2pdf -dEPSCrop result_GP_per.eps
clear;